[output]
root = "result"
# run_name = "run"

[experiment]
mode = "scalar"

[training]
seed = 42
num_train_epochs = 30
logging_strategy = "epoch"
save_strategy = "epoch"
save_total_limit = 1
lr_scheduler_type = "constant"

[training.dpo]
gradient_checkpointing = true
disable_dropout = true
beta = 0.1

[training.lora]
r = 16
lora_alpha = 32
lora_dropout = 0.05

[pairing]
top_k = 2
bottom_k = 2

[critic]
model = "gpt-5.5-pro"
max_retries = 3

[artist]
model = "meta-llama/Meta-Llama-3.1-8B-Instruct"

[artist.generate]
max_new_tokens = 300
num_return_sequences = 8
temperature = 0.95
top_k = 0
top_p = 1.0
min_p = 0.03
# default for llama 3.1 & DPO, add this for other models
# do_sample = true