[output]
root = "result"
# run_name = "run"

[experiment]
mode = "scalar"

[training]
seed = 42
num_train_epochs = 15
logging_steps = 1
save_steps = 1
save_total_limit = 1
lr_scheduler_type = "constant"

[training.lora]
r = 16
lora_alpha = 32
lora_dropout = 0.05

[critic]
model = "gpt-5.5-pro"
max_retries = 3

[artist]
model = "meta-llama/Meta-Llama-3.1-8B-Instruct"

[artist.generate]
max_new_tokens = 300
temperature = 0.95
top_k = 0
top_p = 1.0
min_p = 0.03
# default for llama 3.1 & DPO, add this for other models
# do_sample = true